# Generated by Django 3.2.8 on 2021-10-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_board_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
